name: bwu_testrunner
version: 0.0.1-3
description: bwu_testrunner runs a set of Dart web tests with content_shell and prints a summary.
homepage: https://github.com/bwu-dart/bwu_testrunner
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.12.0+1 <0.13.0'


