name: bwu_testrunner
version: 0.1.0+3
description: bwu_testrunner runs a set of Dart web tests with content_shell and prints a summary.
homepage: https://github.com/bwu-dart/bwu_testrunner
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.12.0+1 <0.13.0'
  path: '>=1.2.2 <1.3.0'
  uuid: '>=0.4.0 <0.5.0'
  logging: '>=0.9.2 <0.10.0'
  watcher: '>=0.9.3 <0.10.0'
dev_dependencies:
  unittest: '>= 0.11.0+4 <0.12.0'


